create table if not exists public.legal_references (
    id bigint generated by default as identity primary key,
    topic text not null,
    law_name text not null,
    article_number integer not null,
    article_title text not null,
    article_text text not null,
    source_url text not null,
    fetched_at timestamptz not null default now(),
    unique (law_name, article_number)
);

create index if not exists legal_references_topic_idx
    on public.legal_references(topic);

alter table public.legal_references enable row level security;

create or replace function public.set_legal_references_fetched_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.fetched_at = now();
    return new;
end;
$$;

drop trigger if exists legal_references_set_fetched_at
    on public.legal_references;

create trigger legal_references_set_fetched_at
before update on public.legal_references
for each row
execute function public.set_legal_references_fetched_at();
